name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run : dotnet restore

    - name: Build app
      run : dotnet build -c Release --no-restore

    - name: Test
      run : dotnet test -c Release --no-build

    - name: Publish
      run: dotnet publish -c Release -o ./out

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:   
        server    : ${{ secrets.FTP_SERVER }}
        username  : ${{ secrets.FTP_USERNAME }}
        password  : ${{ secrets.FTP_PASSWORD }}
        local-dir : ./out/
        server-dir: http/
        dangerous-clean-slate: true
        exclude: .git*
          - **.git*
          - .git*/**
          -  **/.git*/**
